# -*- coding: UTF-8 -*-

from django.utils.translation import ugettext as _
from budget_app.views.helpers import *

# FIXME: Temporary data storage
# in2csv -I /Users/david/Desktop/2021_GeolocalizacionInversiones.xlsx | tail -n +2 | csvcut -c 2,4,6,11,21,23,28 | csvformat -U 2
data = [
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","ESTACIÓN REGENERADORA DE AGUAS RESIDUALES DE REJAS. OBRAS ADECUACIÓN Y MEJORA","BARAJAS","MEDIO AMBIENTE","1456491","69814811.2"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","ESTACIÓN REGENERADORA DE AGUAS RESIDUALES DE VALDEBEBAS. OBRAS DE ADECUACIÓN Y MEJORA","BARAJAS","MEDIO AMBIENTE","1456491","65910244.12"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. M 41B","VICÁLVARO","VIVENDA","739537.79","17560920.16"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. M 39A","VICÁLVARO","VIVENDA","739537.79","17542423.44"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. M 39B","VICÁLVARO","VIVENDA","739537.79","17467699.89"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. T 10BC","VICÁLVARO","VIVENDA","100000","14839949.1"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","AUMENTO DE LA CAPACIDAD DEL DESAGÜE DEL TRAMO INFERIOR ARROYO DE LOS MIGUELES","VICÁLVARO","MEDIO AMBIENTE","1840000","3649768.77"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. M 5C","VICÁLVARO","VIVENDA","150000","14371516.21"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO M5A","VICÁLVARO","VIVENDA","4648011.31","13779959.87"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN8 VICALVARO M5B","VICÁLVARO","VIVENDA","4417354.29","12968982.36"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. M 34B","VICÁLVARO","VIVENDA","150000","14371516.19"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. T 6B","VICÁLVARO","VIVENDA","150000","7420301.26"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. T 6A","VICÁLVARO","VIVENDA","150000","7420301.26"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","UZP 2.03 DESARROLLO DEL ESTE LOS AHIJONES. COMPENSACIÓN","VICÁLVARO","URBANISMO","3770753","15457593.18"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","ESCUELA INFANTIL EN EL CAÑAVERAL. CONSTRUCCIÓN","VICÁLVARO","EDUCACIÓN","200000","4378091.12"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. M 30A","VICÁLVARO","VIVENDA","150000","14971543.41"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VICALVARO. M 30D","VICÁLVARO","VIVENDA","150000","14978398.06"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","CENTRO DE TRATAMIENTO LA PALOMA. SISTEMAS DE DESODORIZACIÓN","VILLA DE VALLECAS","MEDIO AMBIENTE","3008294.3","6146381.6"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","COLECTOR DOBLADO DE VICÁLVARO. CONSTRUCCIÓN","VICÁLVARO","MEDIO AMBIENTE","10387373","14219936.97"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CALLE AYERBE. REMODELACIÓN URBANIZACIÓN","BARAJAS","URBANISMO","1546125.74","1546125.74"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","INTERSECCIONES C/ JOAQUÍN COSTA Y FRANCISCO SILVELA CON C/ LÓPEZ DE HOYOS. REURBANIZACIÓN","CHAMARTÍN","URBANISMO","7332910.48","10247710.27"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","NUEVA PLANTA DE MATERIA ORGÁNICA EN EL PARQUE TECNOLÓGICO DE VALDEMINGÓMEZ","VILLA DE VALLECAS","MEDIO AMBIENTE","5148223.48","31995450.95"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","SISTEMAS DE COMPENSACIÓN. UZP 2-04 LOS BERROCALES","VICÁLVARO","URBANISMO","1870338","22242643.12"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE TECNOLÓGICO DE VALDEMINGÓMEZ. SISTEMAS DE DESODORIZACIÓN BIOMETANIZACION","VILLA DE VALLECAS","MEDIO AMBIENTE","4992180.46","7707989.12"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","CENTRO DE TRATAMIENTO  LAS DEHESAS. SISTEMAS DE DESODORIZACIÓN","VILLA DE VALLECAS","MEDIO AMBIENTE","1605000","5608350"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO BAJO CALZADA C/PLAYA DE RIAZOR,ENTRE C/ALCAÑIZ Y PLAYA AMÉRICA. CONSTRUCCIÓN","BARAJAS","INFRAESTRUCTURAS","71895","10977902.64"],
    ["AYUNTAMIENTO","DEPORTE","UNIDADES DEPORTIVAS PARA LA PRÁCTICA DEL RUGBY EN VILLA DE VALLECAS. CONSTRUCCIÓN","VILLA DE VALLECAS","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","2984098","2984098"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","ENSANCHE DE VALLECAS. ACONDICIONAMIENTO DE CAMINOS Y ZONAS ESTANCIALES","VILLA DE VALLECAS","MEDIO AMBIENTE","2799995","3816995"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","ESCUELA INFANTIL EN EL DISTRITO DE VILLA DE VALLECAS. CONSTRUCCIÓN","VILLA DE VALLECAS","EDUCACIÓN","148853","4619842.92"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","DRENAJE VÍA DE SERVICIO DE LA N-III A LA ALTURA DEL ENSANCHE DE VALLECAS","VICÁLVARO","MEDIO AMBIENTE","2647788","3290553.03"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","ÁMBITO CERRO ALMODÓVAR. EJECUCIÓN DEL BOSQUE METROPOLITANO","VICÁLVARO - VILLA DE VALLECAS","URBANISMO","1500000","4500000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DE SERVICIOS SOCIALES ENSANCHE DE VALLECAS. CONSTRUCCIÓN","VILLA DE VALLECAS","PROTECCIÓN Y PROMOCIÓN SOCIAL","4747744","5932475.08"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CASA DE FAMILIA VILLA DE VALLECAS. CONSTRUCCIÓN","VILLA DE VALLECAS","PROTECCIÓN Y PROMOCIÓN SOCIAL","230000","4330000"],
    ["AYUNTAMIENTO","CULTURA, TURISMO Y DEPORTE","PALACIO ""EL CAPRICHO"". REHABILITACIÓN PARA DESARROLLO MUSEOGRÁFICO","BARAJAS","CULTURA","686001","3672230.89"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO CULTURAL EN VALDERRIVAS, C/ TITANIO. CONSTRUCCIÓN","VICÁLVARO","CULTURA","3187382.74","6716070.26"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","INSTALACIÓN DEPORTIVA ENSANCHE DE VALLECAS (PAU VALLECAS). CONSTRUCCIÓN","VILLA DE VALLECAS","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","6586921.92","11886974.97"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO CULTURAL VALDEBEBAS. CONSTRUCCIÓN","HORTALEZA","CULTURA","231000","4800000"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE DEL PARAÍSO. OBRAS DE ADECUACIÓN Y MEJORA (ID 18: 409)","SAN BLAS-CANILLEJAS","MEDIO AMBIENTE","39995","2151484.88"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO EN VALDEBEBAS. CONSTRUCCIÓN","HORTALEZA","INFRAESTRUCTURAS","1056892","1069467.26"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO EN CANILLEJAS. CONSTRUCCIÓN","HORTALEZA","INFRAESTRUCTURAS","4010540","4146699.92"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","BASE DEL SAMUR C/ REAL DE ARGANDA, 64, VILLA DE VALLECAS. CONSTRUCCIÓN","VILLA DE VALLECAS","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","2234723","2282677.51"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","UNIDAD INTEGRAL DE POLICÍA MUNICIPAL VILLA DE VALLECAS. CONSTRUCCIÓN","VILLA DE VALLECAS","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","166123","6416919.06"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","EDIFICIO A1 C/ARCOS JALÓN, 34. REHABILITACIÓN PARA CENTRO TECNOLOGÍAS INNOVACIÓN Y COMUNICACIÓN","SAN BLAS-CANILLEJAS","OTROS BIENES PÚBLICOS DE CARÁCTER ECONÓMICO","2000000","2000000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DE SERVICIOS SOCIALES EN SAN BLAS, C/POBLADURA DEL VALLE, 13. CONSTRUCCIÓN","SAN BLAS-CANILLEJAS","PROTECCIÓN Y PROMOCIÓN SOCIAL","3418561","3819836.82"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","ÁMBITO CAMPO DE LAS NACIONES. EJECUCIÓN DEL BOSQUE METROPOLITANO","HORTALEZA","URBANISMO","1605614","3770360.12"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","UNIDAD INTEGRAL DE POLICÍA MUNICIPAL CIUDAD LINEAL. CONSTRUCCIÓN","CIUDAD LINEAL","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","2218042","5063513.66"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","BASE DEL SAMUR EN CIUDAD LINEAL, C/ PELOPONESO, 9. CONSTRUCCIÓN","CIUDAD LINEAL","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","1700618","1953606.6"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","CUÑA NORTE DE O´DONELL. EJECUCIÓN DE BOSQUE METROPOLITANO","CIUDAD LINEAL","URBANISMO","2000000","2500000"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE CUÑA VERDE O'DONNELL. AMPLIACIÓN","MORATALAZ","MEDIO AMBIENTE","750908","4651636.6"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE DE LA GAVIA, DISTRITO VILLA DE VALLECAS. OBRAS DE REHABILITACIÓN","VILLA DE VALLECAS","MEDIO AMBIENTE","7930281","18435975.59"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN LA ROSILLA 4","VILLA DE VALLECAS","VIVENDA","5615771.01","10019639.62"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN LA ROSILLA 3","VILLA DE VALLECAS","VIVENDA","4916911.48","11901167.78"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN LA ROSILLA 1","VILLA DE VALLECAS","VIVENDA","4660916.13","14142143.36"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN LA ROSILLA 2","VILLA DE VALLECAS","VIVENDA","4508981.82","10976840.87"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO EN SUPERFICIE MAR DE CRISTAL. CONSTRUCCIÓN","HORTALEZA","INFRAESTRUCTURAS","2200000","2200000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","BASE SAMUR C/ AREQUIPA, 4. CONSTRUCCIÓN","HORTALEZA","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","1471581","2304103.83"],
    ["EMPRESA MUNICIPAL DE SERVICIOS FUNERARIOS Y CEMENTERIOS, S.A.","PORTAVOZ, SEGURIDAD Y EMERGENCIAS","ACTUACIONES EN CEMENTERIO DE LA ALMUDENA","CIUDAD LINEAL","SALUD PÚBLICA","1633241","2733572.16"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","ESCUELA INFANTIL EN CANILLEJAS. CONSTRUCCIÓN (ID 18: 539)","SAN BLAS-CANILLEJAS","EDUCACIÓN","150000","4083665.83"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","PASO INFERIOR BAJO LÍNEA FERROCARRIL POLÍGONO INDUSTRIAL VILLA DE VALLECAS. DESDOBLAMIENTO","PUENTE DE VALLECAS - VILLA DE VALLECAS","INFRAESTRUCTURAS","1000000","3000000"],
    ["EMPRESA MUNICIPAL DE TRANSPORTES, S.A.","MEDIO AMBIENTE Y MOVILIDAD","CONSTRUCCIÓN DE NUEVO CENTRO DE OPERACIONES EN LA ÉLIPA","CIUDAD LINEAL","TRÁFICO, ESTACIONAMIENTO Y TRANSPORTE PÚBLICO","4000000","64418280"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CASA DE LA JUVENTUD C/ RÍO ESMERALDA, 15. CONSTRUCCIÓN","PUENTE DE VALLECAS","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","1162315","1667746.22"],
    ["AYUNTAMIENTO","PORTAVOZ, SEGURIDAD Y EMERGENCIAS","PARQUE DE BOMBEROS Nº 8. REFORMA TORRE MANIOBRAS Y DEPENDENCIAS FORMACIÓN BOMBEROS","PUENTE DE VALLECAS","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","2249573","2749571.51"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","BASE SAMUR PUENTE VALLECAS, AVENIDA BUENOS AIRES, 17. CONSTRUCCIÓN","PUENTE DE VALLECAS","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","2107769","2152880.9"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","UNIDAD INTEGRAL POLICÍA MUNICIPAL PUENTE VALLECAS, AVDA. BUENOS AIRES, 17. CONSTRUCCIÓN","PUENTE DE VALLECAS","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","4773248","5812868.97"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","C/ALCALÁ:TRAMO M-30-QUINTANA.CIUDAD LINEAL.ADECUACIÓN FIRMES Y PAVIMENTOS ACERAS Y CALZADAS","CIUDAD LINEAL","MANTENIMIENTO URBANO","1740691.47","2025095.98"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","APR 13.01 SIERRA TOLEDANA. URBANIZACIÓN","PUENTE DE VALLECAS","URBANISMO","2022643.1","3047111.16"],
    ["EMPRESA MUNICIPAL DE SERVICIOS FUNERARIOS Y CEMENTERIOS, S.A.","PORTAVOZ, SEGURIDAD Y EMERGENCIAS","RENOVACIÓN  TANATORIOS","CIUDAD LINEAL","SALUD PÚBLICA","1850000","2400000"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN SAN FRANCISCO JAVIER VI","PUENTE DE VALLECAS","VIVENDA","9097317.69","11146871.43"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","ZONAS AJARDINADAS DEL DISTRITO C - LAS TABLAS. RED DE AGUA REGENERADA","FUENCARRAL-EL PARDO","MEDIO AMBIENTE","1465385","1629233.03"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DE SERVICIOS SOCIALES SAN DIEGO. AMPLIACIÓN","PUENTE DE VALLECAS","PROTECCIÓN Y PROMOCIÓN SOCIAL","3078710","3343202.81"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN NUESTRA SEÑORA  DE LOS ANGELES 3","PUENTE DE VALLECAS","VIVENDA","6505389.63","9889517.53"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN NUESTRA SEÑORA  DE LOS ANGELES 4","PUENTE DE VALLECAS","VIVENDA","4141352.55","10087069.21"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN NUESTRA SEÑORA  DE LOS ANGELES 2","PUENTE DE VALLECAS","VIVENDA","4946613.07","7640815.83"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN NUESTRA SEÑORA  DE LOS ANGELES 14","PUENTE DE VALLECAS","VIVENDA","11630033.31","21112970.62"],
    ["EMPRESA MUNICIPAL DE TRANSPORTES, S.A.","MEDIO AMBIENTE Y MOVILIDAD","CONSTRUCCIÓN DE NUEVO CENTRO DE OPERACIONES EN LAS TABLAS","FUENCARRAL-EL PARDO","TRÁFICO, ESTACIONAMIENTO Y TRANSPORTE PÚBLICO","1000000","99400000"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PLAZA DE LAS TABLAS. ADECUACIÓN ZONA VERDE Y ESTANCIAL (ID 18: 2531)","FUENCARRAL-EL PARDO","MEDIO AMBIENTE","1332872","1332872"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO CULTURAL C/ PASTORA IMPERIO, 4. CONSTRUCCIÓN","CHAMARTÍN","CULTURA","193560","5193560"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","UNIDAD INTEGRAL POLICÍA DISTRITO RETIRO Y BASE DEL SAMUR. CONSTRUCCIÓN","RETIRO","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","2837629","4325629.26"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","NAVE PARA ALMACÉN DE BOMBEROS EN LA ATALAYUELA. CONSTRUCCIÓN","VILLA DE VALLECAS","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","157587","5424779"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","JARDINES DEL BUEN RETIRO. REHABILITACIÓN INTEGRAL DEL ENTORNO DEL METEREOLÓGICO","RETIRO","MEDIO AMBIENTE","1049260","1120367.1"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","OBRAS EJECUCIÓN NUDO NORTE M-30 MADRID","FUENCARRAL-EL PARDO - CHAMARTÍN","INFRAESTRUCTURAS","30203684","58483881.52"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","BIBLIOTECA DE VILLAVERDE. CONSTRUCCIÓN","VILLAVERDE","CULTURA","331181","6109209.76"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","PASARELA PEATONAL ACCESO CERCANÍAS SAN CRISTÓBAL DE LOS ÁNGELES DESDE Bº DE BUTARQUE","VILLAVERDE","INFRAESTRUCTURAS","2543688.89","2587430.73"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DE MAYORES C/ TELLEZ. CONSTRUCCION","RETIRO","PROTECCIÓN Y PROMOCIÓN SOCIAL","150000","4950000"],
    ["AYUNTAMIENTO","DISTRITO DE SALAMANCA","EDIFICIO SEDE DISTRITO SALAMANCA. OBRAS DE REHABILITACIÓN GENERAL","SALAMANCA","INVERSIONES DE CARÁCTER GENERAL","150000","3517820.88"],
    ["AYUNTAMIENTO","DEPORTE","DEPORTIVO BÁSICO PARQUE LINEAL MANZANARES.CÉSPED ARTIFICIAL EN CAMPO TIERRA,ILUMINACIÓN Y VESTUARIOS","USERA","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","300000","2000000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DE MAYORES Y OTROS USOS POLIVALENTES C/ BRONCE. CONSTRUCCIÓN","ARGANZUELA","PROTECCIÓN Y PROMOCIÓN SOCIAL","100000","7065565.65"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","PLAN ESPECIAL RECOLETOS-PRADO. OBRAS DE URBANIZACIÓN","RETIRO","URBANISMO","888561.01","888561.01"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","REHABILITACIÓN EDIFICIOS TEATRO FERNÁN GÓMEZ","SALAMANCA","CULTURA","1000000","5367550.51"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","INSTALACIONES TEATRO FERNÁN GÓMEZ","SALAMANCA","CULTURA","350000","1644335"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","OBRA CIVIL TEATRO FERNÁN GÓMEZ","SALAMANCA","CULTURA","150000","1331903.914"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO EN VILLAVERDE BAJO CRUCE. CONSTRUCCIÓN (ID 17:4403)","VILLAVERDE","INFRAESTRUCTURAS","5411743","5606124.23"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO EN TRES OLIVOS, BAJO ZONA VERDE EN C/AFUERAS DE VALVERDE. CONSTRUCCIÓN","FUENCARRAL-EL PARDO","INFRAESTRUCTURAS","63507","4262125.12"],
    ["AYUNTAMIENTO","CULTURA, TURISMO Y DEPORTE","BIBLIOTECA MUNICIPAL EN BARRIO DE SAN FERMÍN. CONSTRUCCIÓN","USERA","CULTURA","949398","4028298.49"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","ANTIGUO MERCADO DE LEGAZPI. SUBSANACIÓN DE PATOLOGÍAS","ARGANZUELA","INVERSIONES DE CARÁCTER GENERAL","2000000","3455760"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO CULTURAL Y BIBLIOTECA EN MONTECARMELO. CONSTRUCCIÓN","FUENCARRAL-EL PARDO","CULTURA","231181","5919196.28"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DEPORTIVO C/COSTANILLA DESAMPARADOS, 15 C/V A C/FÚCAR, 6. CONSTRUCCIÓN","CENTRO","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","6000000","21921169.49"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CALLE EDUARDO BARREIROS. REURBANIZACIÓN","VILLAVERDE","URBANISMO","3980206.61","7960413.24"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","OBRA CIVIL TEATRO ESPAÑOL (CALLE DEL PRÍNCIPE, 25)","CENTRO","CULTURA","395000","3251658.339"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","PUERTA DEL SOL. OBRAS DE REMODELACIÓN","CENTRO","URBANISMO","1850000","15178772"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE DE PRADOLONGO, DISTRITO DE USERA. REHABILITACIÓN Y AMPLIACIÓN","ARGANZUELA","MEDIO AMBIENTE","30972","1530972"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","TEATRO ALMENDRALES. REFORMA Y ADAPTACIÓN PARA CENTRO CULTURAL","USERA","CULTURA","300000","3300000"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN VILLAVERDE INGENIEROS","VILLAVERDE","VIVENDA","739537.79","17817208.68"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO CULTURAL Y BIBLIOTECA EN LAS TABLAS. CONSTRUCCIÓN","FUENCARRAL-EL PARDO","CULTURA","231181","6160036.28"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DE MAYORES MIRASIERRA. CONSTRUCCIÓN","FUENCARRAL-EL PARDO","PROTECCIÓN Y PROMOCIÓN SOCIAL","200000","5700000"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO EN LA PLAZA DE SANTO DOMINGO. CONSTRUCCIÓN","CENTRO","INFRAESTRUCTURAS","2548995","3930789.81"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","EDIFICIO C/ CEA BERMÚDEZ, 2. ADAPTACIÓN PARA ESCUELA INFANTIL","CHAMBERÍ","EDUCACIÓN","100000","2800000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","ESCUELA INFANTIL EN EL PASEO DE LA DIRECCIÓN. CONSTRUCCIÓN","TETUÁN","EDUCACIÓN","233878","3483878"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","PISCINA CUBIERTA C/CEA BERMUDEZ. CONSTRUCCIÓN","CHAMBERÍ","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","4796149","5660677.42"],
    ["AYUNTAMIENTO","PORTAVOZ, SEGURIDAD Y EMERGENCIAS","PARQUE DE BOMBEROS Nº 5. OBRAS DE REFORMA INTEGRAL","USERA","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","1489015","3899999"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE DEL GASOMETRO, DISTRITO DE ARGANZUELA. REHABILITACIÓN","ARGANZUELA","MEDIO AMBIENTE","30972","1530972"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO DEPORTIVO LA CEBADA. CONSTRUCCIÓN","CENTRO","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","7893969","12645037.98"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","PLAZA DE ESPAÑA. OBRAS DE REMODELACIÓN","MONCLOA-ARAVACA - CENTRO","URBANISMO","37846325.6","72734074.47"],
    ["AYUNTAMIENTO","CULTURA, TURISMO Y DEPORTE","MUSEO DE SAN ISIDRO. OBRAS ADECUACIÓN PARA SOSTENIBILIDAD","CENTRO","CULTURA","130000","3630000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO JUVENIL ZOFIO. CONSTRUCCIÓN","USERA","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","2970666","5928103.65"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","ANILLO VERDE DE VILLAVERDE. EJECUCIÓN BOSQUE METROPOLITANO","VILLAVERDE","URBANISMO","2446340","2946340"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","BORDE FORESTAL DE ORCASITAS. EJECUCIÓN DE BOSQUE METROPOLITANO","USERA","URBANISMO","1400000","2600000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","EDIFICIO C/ FRANCOS RODRIGUEZ, 77.CONSOLIDACION ESTRUCTURAL Y ADAPTACION A NORMATIVA","MONCLOA-ARAVACA","INVERSIONES DE CARÁCTER GENERAL","1500000","3500000"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CUBRICIÓN DE LA M-30 EN EL ÁMBITO DEL VICENTE CALDERÓN","ARGANZUELA","INFRAESTRUCTURAS","7177593.69","69240950.77"],
    ["AYUNTAMIENTO","CULTURA, TURISMO Y DEPORTE","CASA DE VARGAS. REHABILITACIÓN CASA-PALACIO Y JARDÍN DE FELIPE II","MONCLOA-ARAVACA","CULTURA","730000","1789147.49"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE SAN ISIDRO. REHABILITACIÓN (ID 17: 4302)","CARABANCHEL","MEDIO AMBIENTE","3634826","3684983.99"],
    ["EMPRESA MUNICIPAL DE TRANSPORTES, S.A.","MEDIO AMBIENTE Y MOVILIDAD","CONSTRUCCIÓN ASFALTADO COMPLETO BASE ESCUADRÓN","MONCLOA-ARAVACA","TRÁFICO, ESTACIONAMIENTO Y TRANSPORTE PÚBLICO","1200000","1200009"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","EDIFICIO DOTACIONAL C/EDUARDO MORALES, 28. CONSTRUCCIÓN","CARABANCHEL","INVERSIONES DE CARÁCTER GENERAL","1130555","5300579.67"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","CASA DE CAMPO GENERAL. OBRA CIVIL E INSTALACIONES","MONCLOA-ARAVACA","INVERSIONES DE CARÁCTER GENERAL","110384","2703188.77"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","MADRID ARENA. INSTALACIONES","MONCLOA-ARAVACA","DEPORTES, JUVENTUD  Y ESPARCIMIENTO","201709","3257150.15"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","PABELLÓN DE HEXÁGONOS. REHABILITACIÓN EDIFICIOS E INSTALACIONES","MONCLOA-ARAVACA","INVERSIONES DE CARÁCTER GENERAL","901135","1640902.97"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","PABELLÓN CONVENCIONES. OBRA CIVIL, REHABILITACIÓN EDIFICIOS","MONCLOA-ARAVACA","SECTORES PRODUCTIVOS","396772","1972914.29"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","PABELLÓN DE  AUTORIDADES. REHABILITACIÓN EDIFICIOS","MONCLOA-ARAVACA","INVERSIONES DE CARÁCTER GENERAL","20000","520000"],
    ["MADRID DESTINO, CULT.,TURISMO Y NEGOCIO, S.A.","CULTURA, TURISMO Y DEPORTE","TEATRO AUDITORIO. REHABILITACIÓN EDIFICIOS","MONCLOA-ARAVACA","CULTURA","100000","1681561.36"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","ZONAS VERDES AVDA. RAFAELA YBARRA Y AVDA. LOS POBLADOS, DISTRITO USERA. REHABILITACIÓN","USERA","MEDIO AMBIENTE","27997","1327997"],
    ["AYUNTAMIENTO","CULTURA, TURISMO Y DEPORTE","PABELLÓN DE HEXÁGONOS CASA DE CAMPO. REHABILITACIÓN","MONCLOA-ARAVACA","CULTURA","66000","1310000"],
    ["AYUNTAMIENTO","DISTRITO DE LATINA","ESCUELA DE MÚSICA EN C/ HURTUMPASCUAL, DISTRITO LATINA. CONSTRUCCIÓN","LATINA","EDUCACIÓN","600000","4350000"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","SOTERRAMIENTO AUTOPISTA A5 Y PASEO VERDE DEL SUROESTE. CONSTRUCCIÓN","LATINA","INFRAESTRUCTURAS","3143306","198306762.23"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","PARQUE DE LAS CRUCES, DISTRITO DE CARABANCHEL. REHABILITACIÓN (ID 19: 9283;11756)","CARABANCHEL","MEDIO AMBIENTE","39994","2139994"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","BIBLIOTECA EN EL DISTRITO DE CARABANCHEL. CONSTRUCCIÓN","CARABANCHEL","CULTURA","15374","4427862.68"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","UNIDAD INTEGRAL POLICÍA MUNICIPAL CARABANCHEL. AVDA. CARABANCHEL ALTO, 61. CONSTRUCCIÓN","CARABANCHEL","PROTECCIÓN CIVIL Y SEGURIDAD CIUDADANA","155618","5750244.13"],
    ["EMPRESA MUNICIPAL VIVIENDA Y SUELO, S.A."," VIVIENDA","VIVIENDA DE PROTECCIÓN PÚBLICA BÁSICA ALQUILER. PROMOCIÓN CARABANCHEL 29","CARABANCHEL","VIVENDA","6335104.64","21076560.71"],
    ["AYUNTAMIENTO","DESARROLLO URBANO","PARCELA AVENIDA DEL TALGO, MONCLOA-ARAVACA. EJECUCIÓN BOSQUE METROPOLITANO","MONCLOA-ARAVACA","URBANISMO","1661959","2161959"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO EN ESTACIÓN DE ARAVACA. CONSTRUCCIÓN","MONCLOA-ARAVACA","INFRAESTRUCTURAS","4400000","4540038.8"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","APARCAMIENTO DISUASORIO EN SUPERFICIE AVIACIÓN ESPAÑOLA. CONSTRUCCIÓN","LATINA","INFRAESTRUCTURAS","1755289","1853296.9"],
    ["AYUNTAMIENTO","OBRAS Y EQUIPAMIENTOS","CENTRO MAYORES Y SERVICIOS SOCIALES C/CANAL DE PANAMÁ C/V.CANAL MOZAMBIQUE . CONSTRUCCIÓN","CIUDAD LINEAL","PROTECCIÓN Y PROMOCIÓN SOCIAL","2497575","5664950.84"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","COLECTOR VICÁLVARO A, SECTOR LOS AHIJONES. CONSTRUCCIÓN","VICÁLVARO","MEDIO AMBIENTE","8727458","27487911.64"],
    ["MERCAMADRID, S.A.","ECONOMÍA, INNOVACIÓN Y EMPLEO","MERCAMADRID. MEJORA ACCESOS, CONDICIONES DE MOVILIDAD E INSTALACIONES DE SEGURIDAD","VILLA DE VALLECAS","SECTORES PRODUCTIVOS","1306000","8262129.28"],
    ["MERCAMADRID, S.A.","ECONOMÍA, INNOVACIÓN Y EMPLEO","MERCADOS CENTRALES Y EDIFICACIONES","VILLA DE VALLECAS","SECTORES PRODUCTIVOS","3464000","17007390.94"],
    ["MERCAMADRID, S.A.","ECONOMÍA, INNOVACIÓN Y EMPLEO","AMPLIACIÓN MERCAMADRID. REFORESTACIÓN Y ADECUACIÓN DEL ENTORNO, NUEVOS CENTROS DE FORMACIÓN ALIMENTARIA, APARCAMIENTO Y MEJORA DEL CENTRO ADMINISTRATIVO","VILLA DE VALLECAS","SECTORES PRODUCTIVOS","3214326","25869477.86"],
    ["AYUNTAMIENTO","MEDIO AMBIENTE Y MOVILIDAD","COLECTOR EN C/ EDUARDO BARREIROS. CONSTRUCCIÓN","VILLAVERDE","MEDIO AMBIENTE","1026230","1046872.9"],
]
# Object used to define data as literal. See http://stackoverflow.com/a/2466207
class DataPoint(object):
    def __init__(self, *initial_data, **kwargs):
        for dictionary in initial_data:
            for key in dictionary:
                setattr(self, key, dictionary[key])
        for key in kwargs:
            setattr(self, key, kwargs[key])

def investmentdetails(request, render_callback=None):
    # Get request context
    c = get_context(request, css_class='body-entities', title='')
    entity = get_main_entity(c)
    set_entity(c, entity)

    # Setup active_tab for menu options
    c['active_tab'] = 'investmentdetails'

    # Get the investments breakdown
    c['area_breakdown'] = BudgetBreakdown(['area', 'description'])
    c['policy_breakdown'] = BudgetBreakdown(['policy', 'description'])
    c['department_breakdown'] = BudgetBreakdown(['institution', 'department', 'description'])

    # FIXME: Temporary data storage
    for item in data:
        # Current year
        data_point = DataPoint(year=2021,
            institution=item[0],
            department=item[1],
            description=item[2],
            area=item[3],
            policy=item[4],
            expense=True,
            is_actual=True,
            amount=float(item[5])*100)
        column_name = str(data_point.year)
        c['area_breakdown'].add_item(column_name, data_point)
        c['policy_breakdown'].add_item(column_name, data_point)
        c['department_breakdown'].add_item(column_name, data_point)

        # All years
        data_point.amount = float(item[6])*100
        column_name = "total_"+str(data_point.year)
        c['area_breakdown'].add_item(column_name, data_point)
        c['policy_breakdown'].add_item(column_name, data_point)
        c['department_breakdown'].add_item(column_name, data_point)

    # Get additional information
    populate_entity_descriptions(c, entity)

    return render_response('investmentdetails/index.html', c)
